### ISSUE TITLE
Что-то не так с npm

### ISSUE THREAD

**Issue by dimd13** [A/node-clusterize-cli#10]
Приветствую!
Решил поставить твой замечательный модуль на еще одну тачку, а npm ругается на  неверную контрольную сумму :

```
s# npm i -g node-clusterize-cli 
npm http GET https://registry.npmjs.org/node-clusterize-cli
npm http 304 https://registry.npmjs.org/node-clusterize-cli
npm http GET https://registry.npmjs.org/node-clusterize-cli/-/node-clusterize-cli-1.1.3.tgz
npm http 200 https://registry.npmjs.org/node-clusterize-cli/-/node-clusterize-cli-1.1.3.tgz
npm ERR! Error: shasum check failed for /root/tmp/npm-2076-myqyPbTK/1391233335128-0.9827723589260131/tmp.tgz
npm ERR! Expected: e1958dd3750f36a28e5ee5df929cd17d141787da
npm ERR! Actual:   29647bb822dc9dedc38875bccf5cd71ac6dd0973
npm ERR! From:     https://registry.npmjs.org/node-clusterize-cli/-/node-clusterize-cli-1.1.3.tgz
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "node-clusterize-cli"
npm ERR! cwd /usr/local/lib/node_modules
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/npm-debug.log
npm ERR! not ok code 0
```

Попробуй перезалить на npm.

**Comment by A** [comment]
Возможно, у меня версия NPM с ошибкой в расчете контрольных сумм. Попробую сегодня обновить его и перезалить. А пока вы можете установить модуль с GitHub `npm -g shuvalov-anton/node-clusterize-cli`

**Comment by dimd13** [comment]
Пробовал... От туда тоже с ошибками

```
npm install -g shuvalov-anton/node-clusterize-cli
npm ERR! addLocal Could not install shuvalov-anton/node-clusterize-cli
npm ERR! Error: ENOENT, stat 'shuvalov-anton/node-clusterize-cli'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "shuvalov-anton/node-clusterize-cli"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! path shuvalov-anton/node-clusterize-cli
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
```

**Comment by A** [comment]
Обновил npm и nodejs, залил новую версию. Проверь.

**Comment by dimd13** [comment]
Все отлично..Работает..Спасибо.
